language: java
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  - secure: RA4LKD82cW+0xPayPVAWSpYqJu5uoPcz7oXXYtYNVuilFmS8PGYx0g/BXs4QMvQsGMt6aMLN8m7lMAPN5XTH/8JSeM3VmQ3mdpgNdP+p3CVlwrapZ2lTq27Wb/E8J1CGEHOg76z716t//FUElyC/gdhS+tfBmXk3YanM5fMXEHs=
cache:
  directories:
  - ~/.gradle
  - ~/site-library
before_install:
- openssl aes-256-cbc -K $encrypted_29f3b7c4d8c3_key -iv $encrypted_29f3b7c4d8c3_iv
  -in client_secret.json.enc -out client_secret.json -d
- sudo mkdir -p /usr/local/lib/R/
- mkdir -p site-library
- sudo ln -sFv ~/site-library /usr/local/lib/R/site-library
- wget -N https://downloads.gradle.org/distributions/gradle-2.2.1-bin.zip
- unzip gradle-2.2.1-bin.zip
- export PATH=`pwd`/gradle-2.2.1/bin:$PATH
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu precise/"
- sudo apt-get update
- sudo apt-get install -y r-base-dev=3.1.3-1precise2
- sudo apt-get install -y --force-yes r-base-core=3.1.3-1precise2
- R --version
- sudo Rscript scripts/install_R_packages.R
after_success:
- gradle jacocoTestReport coveralls
